// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC97fVaTbmGsCNYrUHmEFJCP1lPJ_wY_w0',
    appId: '1:935659427392:web:125afeea26fc9c8d64b1a5',
    messagingSenderId: '935659427392',
    projectId: 'fooddeliveryapp-722c6',
    authDomain: 'fooddeliveryapp-722c6.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-722c6.appspot.com',
    measurementId: 'G-S8JX9W8CVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAtwIBCTfnSg4bZKktL7xwOqOE58k3B0M',
    appId: '1:935659427392:android:607da37ae4f40ec064b1a5',
    messagingSenderId: '935659427392',
    projectId: 'fooddeliveryapp-722c6',
    storageBucket: 'fooddeliveryapp-722c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF_BN43QiQJk2EU4Wrj0IlPYioMf7nG4w',
    appId: '1:935659427392:ios:efaafecba9cfae9464b1a5',
    messagingSenderId: '935659427392',
    projectId: 'fooddeliveryapp-722c6',
    storageBucket: 'fooddeliveryapp-722c6.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF_BN43QiQJk2EU4Wrj0IlPYioMf7nG4w',
    appId: '1:935659427392:ios:efaafecba9cfae9464b1a5',
    messagingSenderId: '935659427392',
    projectId: 'fooddeliveryapp-722c6',
    storageBucket: 'fooddeliveryapp-722c6.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC97fVaTbmGsCNYrUHmEFJCP1lPJ_wY_w0',
    appId: '1:935659427392:web:46e64f8fe41d8cdc64b1a5',
    messagingSenderId: '935659427392',
    projectId: 'fooddeliveryapp-722c6',
    authDomain: 'fooddeliveryapp-722c6.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-722c6.appspot.com',
    measurementId: 'G-K6XZ5RKN82',
  );
}
